force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Aggregated_performance_metrics__c.field-meta.xml
<CustomField>
    <fullName>Aggregated_performance_metrics__c</fullName>
    <label>Aggregated performance metrics</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Performance_Score__c.field-meta.xml
<CustomField>
    <fullName>Employee_Performance_Score__c</fullName>
    <label>Employee Performance Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/PerformanceReportBatch.cls
public class PerformanceReportBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Employee_Performance_Score__c,Aggregated_performance_metrics__c
            FROM Employee__c
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Employee__c> employeeList) {
        system.debug('Employee List is '+employeeList);
        
        Decimal totalPerformanceScore = 0;
        Integer totalEmployeeCount = 0;

        
        for (Employee__c emp : employeeList) {
            if (emp.Employee_Performance_Score__c != null) {
                totalPerformanceScore += emp.Employee_Performance_Score__c;
                totalEmployeeCount++;
            }
        }
         system.debug('Total Perfromance Score'+totalPerformanceScore);
         system.debug('Total Employee Count'+totalEmployeeCount);
        
        // Calculate the average score
        Decimal averageScore = totalEmployeeCount > 0 ? totalPerformanceScore / totalEmployeeCount : 0;
        
        system.debug('Average Score is'+averageScore);
        
        // Update all Employee__c records with the average score
        for (Employee__c emp : employeeList) {
            emp.Aggregated_performance_metrics__c = averageScore;
        }

        update employeeList;
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Batch Class is completed');
    }
}