force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Date_of_Hire__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Hire__c</fullName>
    <label>Date of Hire</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <label>Employee ID</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Performance_Score__c.field-meta.xml
<CustomField>
    <fullName>Employee_Performance_Score__c</fullName>
    <label>Employee Performance Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Performance_Review__c/Performance_Review__c.object-meta.xml
<CustomObject>
    <label>Performance Review</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Performance Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Performance_Review__c/fields/Employees__c.field-meta.xml
<CustomField>
    <fullName>Employees__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Performance Reviews (Employee)</relationshipLabel>
    <relationshipName>Performance_Reviews1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Performance_Review__c/fields/FeedBack__c.field-meta.xml
<CustomField>
    <fullName>FeedBack__c</fullName>
    <label>FeedBack</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Performance_Review__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Performance Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/PerformanceManager.cls
public class PerformanceManager {

    //**Method 1: createPerformanceReview**
        public static void createPerformanceReview(Integer EmyId,Date ReviewDate,String Feedback){
        
        Employee__c empyName=[SELECT Id, Name, Employee_ID__c FROM Employee__c where Employee_ID__c =:EmyId LIMIT 1];
        system.debug('Employee Name'+empyName.Name);
        Performance_Review__c perComp=new Performance_Review__c();
        perComp.Employees__c = empyName.Id;
        system.debug('Performance Employee Data'+ perComp.Employees__c);
        perComp.Review_Date__c = ReviewDate;
        perComp.FeedBack__c = Feedback;
        insert perComp;
        
     } 
    
    //Integer empId=2302;
    //Date da = Date.valueOf('2024-03-16');
    //String stg = 'Average';
    //PerformanceManager.createPerformanceReview(empId,da,stg);
    
    
    //- **Method 2: calculateOverallScore**
    public static String calculateOverallScore(Integer EmploId){
         Performance_Review__c performanceData=
             [SELECT Id, Name, Review_Date__c,Employees__c,
              Rating__c,Score__c,Employees__r.Employee_ID__c FROM Performance_Review__c where Employees__r.Employee_ID__c =:EmploId];
        
        system.debug('Empolyees Records'+performanceData);
        
       
         if(performanceData.Rating__c=='1')
         {
            return '15';     
         }
         else if(performanceData.Rating__c=='2')
         {
            return 'Between 16 to 25'; 
         }
         else if(performanceData.Rating__c=='3')
         {
            return 'Between 26 to 50';         }
         else if(performanceData.Rating__c=='4')
         {
             return 'Between 51 to 75';  
         }
        else{
            return 'Between 76 to 100';
        }
                
    }
    //String PerformanceScore = PerformanceManager.calculateOverallScore(2302);
    //system.debug('Performance Score is '+PerformanceScore);

    
    //**Additional Method: getEmployeeDetails**
    public static List<Employee__c> employeeDetails(Integer EmplId){
        return [SELECT Id, Name, Department__c, Date_of_Hire__c, Employee_ID__c FROM Employee__c where Employee_ID__c =:EmplId LIMIT 1];
    }
    
    //List<Employee__c> employeeData = PerformanceManager.employeeDetails(2302);
    //system.debug('EmployeeData'+employeeData);
    
    // ** Trigger Method calculateOverallScor
    public static void calculateOverallScor(List<Performance_Review__c> performanceReviews) {
        List<Employee__c> employeesToUpdate = new List<Employee__c>();
        for (Performance_Review__c performanceReview : performanceReviews) {
            if(performanceReview.Rating__c=='1'){
                performanceReview.Score__c=15;
                updateEmployeeDepartment(performanceReview, 15 , employeesToUpdate);
            }else if(performanceReview.Rating__c=='2'){
                performanceReview.Score__c=30;
                updateEmployeeDepartment(performanceReview, 30, employeesToUpdate);
            }else if(performanceReview.Rating__c=='3'){
                performanceReview.Score__c=50;
                updateEmployeeDepartment(performanceReview, 50 , employeesToUpdate);
            }else if(performanceReview.Rating__c=='4'){
                performanceReview.Score__c=70;
                updateEmployeeDepartment(performanceReview, 70 , employeesToUpdate);
            }else{
                performanceReview.Score__c=100;
                updateEmployeeDepartment(performanceReview, 100 , employeesToUpdate);
            }
            
            if (!employeesToUpdate.isEmpty()) {  
                update employeesToUpdate; 
            }
        
          }
       }
        
      private static void updateEmployeeDepartment(Performance_Review__c performanceReview, Integer score, List<Employee__c> employeesToUpdate) {
                 if (performanceReview.Employees__c != null) {
                           Employee__c employee = new Employee__c(
                                                  Id = performanceReview.Employees__c,
                                                  Employee_Performance_Score__c = score );
                           employeesToUpdate.add(employee);
     }
        
       
    }// method is end 
    
    
    

    
    
    
   }