force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Health Care</fullName>
            </value>
            <value>
                <fullName>Medico</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>North-East</fullName>
            </value>
            <value>
                <fullName>South-West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerList.cls
public class CustomerList {

    @AuraEnabled(cacheable=true)
    public static list<Customer__c> custmlist(String keyword){
        String searchKey = '%' + keyword + '%';
        return [SELECT Id, Name, Email__c, Phone_Number__c FROM Customer__c where Name LIKE :searchKey];      
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Customer__c> searchRecords(String searchTerm, String industry, String region) {
        String searchKey = '%' + searchTerm + '%';
        String industryQuery = String.isNotBlank(industry) ? 'AND Industry__c = :industry' : '';
        String regionQuery = String.isNotBlank(region) ? 'AND Region__c = :region' : '';
        String queryString = 'SELECT Id, Name, Phone_Number__c, Industry__c, Region__c FROM Customer__c WHERE Name LIKE :searchKey ' + industryQuery + ' ' + regionQuery;
        return Database.query(queryString);
    }

    
   @AuraEnabled(cacheable=true)
    public static List<Customer__c> searchCustomers(String customerName, Integer minAge, Integer maxAge) {
        String cumlist = 'SELECT Name, Age__c, Industry__c, Region__c FROM Customer__c WHERE Name LIKE :customerName';
        if (minAge != null) {
            cumlist += ' AND Age__c >= :minAge';
        }
        if (maxAge != null) {
            cumlist += ' AND Age__c <= :maxAge';
        }
        System.debug('Search Customer Returns'+Database.query(cumlist));
        return Database.query(cumlist);

    }


}