force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Health Care</fullName>
            </value>
            <value>
                <fullName>Medico</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>North-East</fullName>
            </value>
            <value>
                <fullName>South-West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/customerClass.cls
public class customerClass {

    @AuraEnabled(cacheable=true)
    public static List<Customer__c> displayCustomerByAge(List<Customer__c> Customers,Integer searchItem, Integer minAge, Integer maxAge){
        List<customer__c> customerList=new List<Customer__c>();
        
        for(Customer__c c:Customers){
            if((minAge == null || c.Age__c < minAge) && (maxAge != null && c.Age__c <= 30)){
            String key='%'+searchItem+'%';
            customerList=[select name,Age__c,Region__c,Industry__c from Customer__c where Name like:key];
        }
            else{
            customerList=[select name,Age__c,Region__c,Industry__c from Customer__c];
               }
               
            if((minAge != null && maxAge == null && c.Age__c > 15)){
            String key='%'+searchItem+'%';
            customerList=[select name,Age__c,Region__c,Industry__c from Customer__c where Name like:key];
        }
            else{
            customerList=[select name,Age__c,Region__c,Industry__c from Customer__c];
               }
               
             if((minAge != null && maxAge != null && c.Age__c >= minAge && c.Age__c <= maxAge)){
            String key='%'+searchItem+'%';
            customerList=[select name,Age__c,Region__c,Industry__c from customer__c where Name like:key];
        }
            else{
            customerList=[select name,Age__c,Region__c,Industry__c from Customer__c];
               }
             
        }
        return customerList;
    }
}