force-app/main/default/objects/Care_Program__c/Care_Program__c.object-meta.xml
<CustomObject>
    <label>Care Program</label>
    <nameField>
        <label>Care Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Program__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Hydrabad</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Care_Program_Location__c.field-meta.xml
<CustomField>
    <fullName>Care_Program_Location__c</fullName>
    <label>Care Program Location</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Channel_Program__c.field-meta.xml
<CustomField>
    <fullName>Channel_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Program</label>
    <referenceTo>Care_Program__c</referenceTo>
    <relationshipLabel>Subscription</relationshipLabel>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SubscriptionHandler.cls
public class SubscriptionHandler {
    
    public static void updateLoaction(List<Subscription__c> subList){
        set<Id> careProgramIds=new set<Id>();
        if(!subList.isEmpty()){
            for(Subscription__c sub: subList){
                careProgramIds.add(sub.Channel_Program__c);
            }
        }
        
        Map<String,String> careProgramMap =new Map<String,String>();
        if(!careProgramIds.isEmpty()){
            for(Care_Program__c cp: [select id, Location__c from Care_Program__c where ID IN :careProgramIds]){
                careProgramMap.put(cp.Id, cp.Location__c);
            }
        }
        
        for(Subscription__c sb: subList){
            sb.Care_Program_Location__c = careProgramMap.get(sb.Channel_Program__c);
        }
    }

}